// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ai-assistant-empty-state'
  | 'ai-assistant-new-thread'
  | 'ai-assistant-placeholder'
  | 'ai-assistant-pref-api-key-help'
  | 'ai-assistant-pref-description'
  | 'ai-assistant-pref-save'
  | 'ai-assistant-pref-status-saved'
  | 'ai-assistant-pref-status-valid'
  | 'ai-assistant-pref-validate'
  | 'ai-assistant-scope-collection'
  | 'ai-assistant-scope-manual-selection'
  | 'ai-assistant-scope-paper'
  | 'ai-assistant-scope-pdf'
  | 'ai-assistant-send'
  | 'ai-assistant-settings'
  | 'ai-assistant-sidebar-title'
  | 'ai-assistant-toggle-shortcut';
