// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "customPresets": string;
      "model": string;
      "maxContextBudget": number;
      "sidebarVisible": boolean;
      "evidenceEnabled": boolean;
      "evidenceProviderMode": string;
      "tavilyApiKey": string;
    };
  }
}
