// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "baseURL": string;
      "model": string;
      "maxContextBudget": number;
      "keyboardShortcut": string;
    };
  }
}
